### ISSUE TITLE
Display "metrics of interest" about each RTP stream

### ISSUE THREAD

**Issue by henbos** [Orphis/webrtc-sandbox#12]
We currently display resolution and frame rate, e.g. `Layer 0 1280x720 29.8 fps`.

I think we should also display the following metrics of interest:
- Encoder implementation name
- Average encode time (per encoded frame)
- Average QP (per encoded frame)
- Quality limitation reason
- Target bitrate
- Actual bitrate (per RTP stream) including headers + payload
- Total key frame count

**Comment by henbos** [comment]
And, of course,
- Scalability mode (the actual one)

**Comment by Orphis** [comment]
Don't forget about the codec used also. We want to be mixed-codec simulcast ready!

**Comment by henbos** [comment]
Good thinkin!
